### ISSUE TITLE
[Suggestion] Add an option to wipe the game's save data before restarting...

### ISSUE THREAD

**Issue by PlayerGameSK** [Lynx64/CloseRestartGamePlugin#1] opened 2024-01-05 14:22 UTC
So I'm not sure if this is even being maintained anymore, but if at all possible, an option to remove the save data of the current game and then restarting it (by holding a certain button combo or something) could really be useful for speedrunners, because for example in Splatoon 1 once you get past the initial tutorial and want to reset your run, you have to either switch to an alt account with no save, or manually delete it through the Save Management / SaveMii, which can get a bit annoying.

In case this does actually end up being added, it should definitely be disabled by default, just to prevent people from accidentally deleting their saves lol

**Comment by Andrew1Hawes** [comment] 2024-01-14 20:54
That is a cool idea! I wouldn't mind taking a look at it but I am very busy at the moment (with wii u and other stuff).

**Comment by Andrew1Hawes** [comment] 2024-04-18 06:46
To update you, for now i'll have a link in the config menu to Data Management, then when you back out it will return you to the Wii U Menu without the long OS relaunch.

Note: normally you will require a GamePad so I recommend [Better Settings](https://github.com/Fangal-Airbag/Better-Settings) so you can also use a Pro Controller.

**Comment by PlayerGameSK** [comment] 2024-04-18 07:34
Sounds good, thanks for taking the time to implement this!

**Comment by Andrew1Hawes** [comment] 2024-05-13 20:12
@PlayerGameSK Do you mind giving this a test run? As far as I know everything is working as intended.
Of course the final release will have the option hidden by default.
[CloseRestartGamePlugin.zip](https://github.com/Lynx64/CloseRestartGamePlugin/files/15299477/CloseRestartGamePlugin.zip)

**Comment by PlayerGameSK** [comment] 2024-05-13 23:51
> @PlayerGameSK Do you mind giving this a test run? As far as I know everything is working as intended. Of course the final release will have the option hidden by default. [CloseRestartGamePlugin.zip](https://github.com/Lynx64/CloseRestartGamePlugin/files/15299477/CloseRestartGamePlugin.zip)

Okay, so I gave it a shot and it seems to be mostly fine, however: 

1.) The "Prefer "LaunchMenuFromHBM" functions" option is kinda confusing, and I'm not entirely sure what it means. 

2.) "Close and delete save data" does indeed close the game, however the save data seems to be intact... or well, at least after testing it with Splatoon, the save was still there after I restarted.

**Comment by Andrew1Hawes** [comment] 2024-05-14 18:44
Splatoon works for me on Disc/MLC. I'm guessing you're on USB. Can you see if it's working now. I'm deleting it earlier and without a flush.
[CloseRestartGamePlugin.zip](https://github.com/Lynx64/CloseRestartGamePlugin/files/15312652/CloseRestartGamePlugin.zip)

**Comment by PlayerGameSK** [comment] 2024-05-17 01:34
No, actually, I tested the Japanese version installed onto the System Memory, haven't tried disc yet. 
Same results with the latest one you posted... (sorry for the late reply btw)

**Comment by Andrew1Hawes** [comment] 2024-06-30 01:58
[CloseRestartGamePlugin.zip](https://github.com/user-attachments/files/16042675/CloseRestartGamePlugin.zip)

Sorry, I got busy. I'm really hoping that it's as simple as initialising ACT, otherwise I'm not sure.
I've also switched to using the 'auto' deviceType instead of manually choosing MLC or USB, hopefully this doesn't bring issues of it's own.

Incase it still doesn't work, I'm displaying the return value from the Delete function. 0 = success, any other values let me know what you get. (For your own curiosity you can see what value means vaguely what here [ACP results](https://wut.devkitpro.org/group__nn__acp__result.html).)

**Comment by Andrew1Hawes** [comment] 2024-07-14 15:00
> I've also switched to using the 'auto' deviceType instead of manually choosing MLC or USB, hopefully this doesn't bring issues of it's own.

Nevermind, looks like this doesn't work. I'll go back to my previous code.

**Comment by Andrew1Hawes** [comment] 2024-07-14 16:36
Fixed the `DEVICE_NOT_FOUND` error.
[CloseRestartGamePlugin.zip](https://github.com/user-attachments/files/16228103/CloseRestartGamePlugin.zip)

**Comment by PlayerGameSK** [comment] 2024-07-15 22:28
So I just tried the latest version and after using the "Close and delete save data" option, it closed the game and then gave me an error pop-up in the upper-left corner of the screen saying "ACPRemoveSaveDir returned -201" (see attachment below) 

![Untitled](https://github.com/user-attachments/assets/0c327cea-94a9-4410-ad65-f40f056948e6)

**Comment by Andrew1Hawes** [comment] 2024-07-17 18:29
Thank you for all the testing, and sorry for any inconvenience. I'm using a different, simpler approach now. Praying this works 🙏😆. @PlayerGameSK 
[CloseRestartGamePlugin.zip](https://github.com/user-attachments/files/16273260/CloseRestartGamePlugin.zip)

**Comment by PlayerGameSK** [comment] 2024-07-19 18:48
> Thank you for all the testing, and sorry for any inconvenience. I'm using a different, simpler approach now. Praying this works 🙏😆. @PlayerGameSK [CloseRestartGamePlugin.zip](https://github.com/user-attachments/files/16273260/CloseRestartGamePlugin.zip)

Yup, seems to work fine now. Thanks for taking the time to implement this!

**Comment by PlayerGameSK** [comment] 2024-07-19 19:03
Well, actually, after using the "Close and delete save data" option once, it just seems to wipe my save for that game every time I try a regular Restart, or even just closing the game normally through the Wii U Home button menu, which I assume is not the intended behavior...

**Comment by Andrew1Hawes** [comment] 2024-07-20 21:24
> Yup, seems to work fine now. Thanks for taking the time to implement this!

Yes! Awesome! It was a pain but we did it.

> Well, actually, after using the "Close and delete save data" option once, it just seems to wipe my save for that game every time I try a regular Restart, or even just closing the game normally through the Wii U Home button menu, which I assume is not the intended behavior...

Hmm, I can't replicate it on my end, and I've double checked the code. It's likely caused by something else, maybe a cache issue 🤔. Thanks for letting me know.

**Comment by Andrew1Hawes** [comment] 2024-07-21 00:20
New build to test when you have the time. Please check that the delete still works in the first place, and if you can reproduce the issue you had above. I've also added a notification when deletion succeeds `"User save data has been deleted"` , so when the plugin attempts to delete you'll always get some kind of notification.
[CloseRestartGamePlugin.zip](https://github.com/user-attachments/files/16322676/CloseRestartGamePlugin.zip)

**Comment by Andrew1Hawes** [comment] 2024-09-03 01:16
It's unlikely I'll add a restart option so I'm marking this as completed.

**Closed as completed** 2024-09-03 01:16 UTC
Labels: enhancement
